seq=("ACCCCCTGCATACACTAATTCTTTCACACGTGGTGTTTATTACCCTGACAAAGTTTTCAGATCCTCAGTTTTACATTCAACTCAGGACTTGTTCTTACCTTTCTTTTCCAATGTTACTTGGTTCCATGCTATACATGTCTCTGGGACCAATGGTACTAAGAGGTTTGATAACCCTGTCCTACCATTTAATGATGGTGTTTATTTTGCTTCCATGAGAGTCTAACATAATAAGAGGCTGGATTTTTGGTACTACTTTAGATTCGAAGACCCAGTCCCTACTTATTGTTAATAACGCTACTAATGTTGTTATTAAAGTCTGTGAATTTCAATTTTGTAATGATCCATTT")

size=len(seq)   #to calculate total number of A,T,G,C
print("The length of sequence is: ",size)

g_count=seq.count("G")
c_count=seq.count("C")

total_GC = g_count + c_count

GC_content= (total_GC/size)*100
print("The GC Content is : ",GC_content)
        
        
#GC_content= (seq.count("G")+seq.count("C")/len(seq) )*100
